environment: local

port: 8080

dynamodb:
  region: us-west-2
  ak: acoimy
  sk: g3gifr
  endpoint: http://localhost:8000

service-name:
  binance-future: BNF
  binance-spot: BNS

binance-adaptor-future-usdt:
  base-url:
  new-order:
  klines-candle-stick: