environment: local
health-check-msg: "local-success"

port: 8080

dynamodb:
  region: us-west-2
  ak: lc383f
  sk: jmtcmg
  endpoint: http://localhost:8000

service-name:
  binance-future: BNF
  binance-spot: BNS

binance-adaptor-future-usdt:
  base-url: https://hqkzntajki.execute-api.ap-southeast-1.amazonaws.com/prd-adaptor-binance-stg
  new-order: /fapi/v1/order
  klines-candle-stick: /fapi/v1/klines